name: buf-pull-request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-action@v1
        with:
          # The 'main' branch of the GitHub repository that defines the module.
          against: "https://github.com/beerproto/beerproto.git#branch=master"
